### PR TITLE
#53 Added support to login using email

### PR DESCRIPTION
**Pull request by nasirhjafri**

### CODE REVIEW

**Comment by nasirhjafri** [comment]
> See my comment

Ticket says the username and email both to be case insensitive. 
cc: @andrewtpham

**Comment by andrewtpham** [comment]
I was thinking about what @odenypeter had told me how it worked in the past for Activity (please correct me if I'm mis-stating anything). For example when a user creates an account and whether they use `Test@gmail.com` or `test@gmail.com`, the app prior to saving to the Backend will convert it and store it using a standard way, for example `lower case`. Then when a user enters `Test@gmail.com` or `test@gmail.com` in the Frontend, when it submits to the backend, it will be converted to lower case before checking if it existing/correct credentials.

Is that how it works and what `iexact` is doing? And is this even how it should be implemented?

**Comment by odenypeter** [comment]
@nasirhjafri 
It's okay for email to be case insensitive, since email providers treats them so. But usernames should never be case insensitive.
@andrewtpham I mentioned this in our discussion

**Comment by ninetteadhikari** [comment]
@odenypeter @andrewtpham I also think both username and email should be case insensitive. 
Any use case on why `username` should be case sensitive? I have also been looking online and it seems like it is majority time case insensitive.

**Comment by andrewtpham** [comment]
> @nasirhjafri
> It's okay and recommended that emails be case insensitive, since email providers treats them so. But usernames should never be case insensitive.
> @andrewtpham I mentioned this in our discussion

Hi @odenypeter could you provide an explanation or example of why `username` should NOT be case insensitive? I would assume we want case insensitivity for email and username since both can be used for login since we dont want two usernames of `AndrewPham` or `andrewpham`. I'm not sure I understand why we would have it for email but not username. 

I'm reading some articles and it seems like others seem to think the same: https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive
https://sqa.stackexchange.com/questions/15133/should-username-login-id-be-case-sensitive

**Comment by odenypeter** [comment]
@andrewtpham @ninetteadhikari 
We've extended Django user model, in this model, username is unique, this means that, If I register with PETER, Peter, peter. All these 3 names will be saved as unique on the database. 
With @nasirhjafri logic, every time this 3 users try login in, it will use the first result matching the case insensitive check, that means the previous 2 users will never login.
The are options:
1. Do a case-insestive check in the DB before saving a new user
2. Convert all usernames to lowercase/uppercase when registering so that django can reject any mixed-cased but same names that already exist on the DB

So my argument is more on our underlying implementation and the potential issues, than what's out theree.

**Comment by ninetteadhikari** [comment]
ah I see. Thanks @odenypeter that makes sense! 💡 
From my end was suggesting the case insensitive option to make it easier for the users so that they don't have to remember if they registered as 'Ninette' or 'ninette'.

Either of the 2 options suggested are great. @odenypeter @nasirhjafri let me know which one you prefer then I can create a ticket to address the issue. Or do you think it can be added to this PR?

**Comment by nasirhjafri** [comment]
> @andrewtpham @ninetteadhikari
> We've extended Django user model, in this model, username is unique, this means that, If I register with PETER, Peter, peter. All these 3 names will be saved as unique on the database.
> With @nasirhjafri logic, every time these 3 users try loging in, it will use the first result matching the case insensitive check, that means the previous 2 users will never login.
> There are options:
> 
> 1. Do a case-insensitive check in the DB before saving a new user
> 2. Convert all usernames to lowercase/uppercase when registering so that django can reject any mixed-cased but same names that already exist on the DB
> 
> So my argument is more on our underlying implementation and the potential issues, than what's out there.

Hi @odenypeter with the extended model, if you register a user with username PETER and then again try to register a new user with username Peter it will throw an error saying that username already exists. So its not possible that three different users will be created. 
You can try it at https://dots-be-dev.hikaya.dev/docs
cc: @andrewtpham / @ninetteadhikari

**Comment by andrewtpham** [comment]
To summarize the conversation, it sounds like @nasirhjafri current implement already solves this username case insensitivity. I also like the idea of what @odenypeter suggested:
> Convert all usernames to lowercase/uppercase when registering so that django can reject any mixed-cased but same names that already exist on the DB

If you all agree we can merge this PR.

**Pull request merged**
